### ISSUE TITLE
Example lack mongodb information

### ISSUE THREAD

**Issue by senpl** [apiaryio/dredd-example#23]
Currently example tries to connect to mongodb. But mongodb start is not covered in example.

**Comment by honzajavorek** [comment]
Hmm... in this case, that's because MongoDB start/shutdown is covered by the respective CI services (Travis CI, CircleCI, AppVeyor).

**Comment by honzajavorek** [comment]
Starting MongoDB itself is usually handled by the operation system etc. and I'd say it's out of the scope of the example.
